### ISSUE TITLE
... how to use it as server?

### ISSUE THREAD

**Issue by luX0r-reload** [rikulo/socket.io-dart#22]
Hi. Thanks for your port.
I see your dart server sample, but how can I install it as server and launch it?
I worked with php websocket server and launch it by terminal with command php myws.php.
I'm new to Dart so I'm sorry if my question seems to be stupid but I haven't found any docs on it.

Thanks in advance.

**Comment by jumperchen** [comment]
FYI: https://github.com/rikulo/socket.io-dart/tree/master/example
or integrate with [StreamServer](https://github.com/rikulo/stream)

For example in `main.dart`
```
import 'package:socket_io/socket_io.dart' as io;

void main() {
    final socketServer = new io.Server(server: new StreamServer(), options: ifAny);
}
```
After finish your main function, then you can run with the following command in a terminal.
```
dart main.dart
```

More details, please take a look at https://dart.dev/tools/dart-vm

**Comment by luX0r-reload** [comment]
Many thanks.

**Comment by luX0r-reload** [comment]
I installed the dart server and it's running. When I try to connect the client to it. The console output on the server is:
```
connection default namespace
2020-05-13 11:31:14.472794:stream:1
SHOUT: 2020-05-13 11:31:14.472471:Bad state: Header already sent
#0      _HttpResponse.statusCode= (dart:_http/http_impl.dart:862:35)
#1      PollingTransport.doWrite.<anonymous closure> (package:socket_io/src/engine/transport/polling_transport.dart:269:11)
#2      PollingTransport.doWrite (package:socket_io/src/engine/transport/polling_transport.dart:302:14)
#3      PollingTransport.write (package:socket_io/src/engine/transport/polling_transport.dart:246:5)
#4      PollingTransport.send.<anonymous closure> (package:socket_io/src/engine/transport/polling_transport.dart:235:12)
#5      PacketParser.encodePayload.<anonymous closure> (package:socket_io_common/src/engine/parser/parser.dart:212:22)
#6      PacketParser.map.<anonymous closure> (package:socket_io_common/src/engine/parser/parser.dart:229:25)
#7      _rootRunUnary (dart:async/zone.dart:1192:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#13     Future.wait.<anonymous closure> (dart:async/future.dart:402:22)
#14     _rootRunUnary (dart:async/zone.dart:1192:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#19     Future._complete (dart:async/future_impl.dart:516:7)
#20     new Future.microtask.<anonymous closure> (dart:async/future.dart:202:16)
#21     _rootRun (dart:async/zone.dart:1180:38)
#22     _CustomZone.run (dart:async/zone.dart:1077:19)
#23     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#25     _rootRun (dart:async/zone.dart:1184:13)
#26     _CustomZone.run (dart:async/zone.dart:1077:19)
#27     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#29     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#31     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
This is the simple dart client:
```
import 'package:socket_io_client/socket_io_client.dart' as IO;
void main() {
  IO.Socket socket = IO.io('http://0.0.0.0:3000');
  socket.on('connect', (_) {
    print('connect');
    socket.emit('msg', 'TEST MESSAGE!');
  });
  socket.on('event', (data) => print(data));
  socket.on('disconnect', (_) => print('disconnect'));
  socket.on('fromServer', (_) => print(_));
}
```
Any suggestions?

**Comment by jumperchen** [comment]
FYI: https://github.com/rikulo/socket.io-client-dart/tree/master/test
This example works well.

**Comment by luX0r-reload** [comment]
Yes it works! Thanks.

**Comment by luX0r-reload** [comment]
Hi, just another question.
In socket.io documentation seems to be possible to emit message only for users join to a specific room. In dart server side I can join a user to a room by:

`client.join(room);`

but emit with this code:

`io.in(room).emit('message', 'what is going on, party people?');`

Doesn't work. What's wrong?

**Comment by jumperchen** [comment]
FYI: https://github.com/rikulo/socket.io-dart/blob/master/lib/src/server.dart#L386

For example,
```
server.to(room).emit('message', 'what is going on, party people?');
```

**Comment by luX0r-reload** [comment]
Fine!

**Comment by DomingoMG** [comment]
I am trying to start the server with websocket but I get the address 0.0.0.0:3000

Is there something I am doing wrong?

```
import 'package:socket_io/socket_io.dart';

void main() {
  // Dart server
  var io = Server();
  io.on('connection', (client) {
    final headers = client.handshake['headers'];
    headers.forEach((k, v) => print('$k => $v'));

    print('connection default namespace');
    client.on('msg', (data) {
      print('data from default => $data');
      client.emit('fromServer', '$data');
    });
  });
  io.listen(3000);
}
```

```
PS D:\Applications\server> dart .\bin\server.dart
2020-06-05 11:34:36.532261:stream:0
INFO: Rikulo Stream Server 2.5.0 starting on 0.0.0.0:3000
```

**Comment by jumperchen** [comment]
Yes, it's expected as `localhost`.
