### ISSUE TITLE
SHOUT : Bad state: Header already sent with Example code

### ISSUE THREAD

**Issue by irfanbacker** [rikulo/socket.io-dart#26]
Tried this package for the first time with the given example code but couldnt get it working. Is there something wrong i am doing?
I dont understand what the problem is.

### The code run:
```dart
import 'package:socket_io/socket_io.dart';
import 'package:socket_io_client/socket_io_client.dart' as IO;

void main(){
  var io = Server();
  io.on('connection', (client) {
    print('connection default namespace');
    client.on('msg', (data) {
      print('data from default => $data');
      client.emit('fromServer', "ok");
    });
  });
  io.listen(3000);

  // Dart client
  IO.Socket socket = IO.io('http://localhost:3000');
  socket.on('connect', (_) {
    print('connect');
    socket.emit('msg', 'test');
  });
  socket.on('event', (data) => print(data));
  socket.on('disconnect', (_) => print('disconnect'));
  socket.on('fromServer', (_) => print(_));
}
```

### Logs:
```
2020-08-06 21:08:02.216756:stream:0
INFO: Rikulo Stream Server 2.5.1 starting on 0.0.0.0:3000
Home: /mnt/DATA/Flutter/musync/lib/services
connection default namespace
2020-08-06 21:08:02.289317:stream:1
SHOUT: 2020-08-06 21:08:02.289054:Bad state: Header already sent
#0      _HttpResponse.statusCode= (dart:_http/http_impl.dart:858:35)
#1      PollingTransport.doWrite.<anonymous closure> (package:socket_io/src/engine/transport/polling_transport.dart:269:11)
#2      PollingTransport.doWrite (package:socket_io/src/engine/transport/polling_transport.dart:302:14)
#3      PollingTransport.write (package:socket_io/src/engine/transport/polling_transport.dart:246:5)
#4      PollingTransport.send.<anonymous closure> (package:socket_io/src/engine/transport/polling_transport.dart:235:12)
#5      PacketParser.encodePayload.<anonymous closure> (package:socket_io_common/src/engine/parser/parser.dart:212:22)
#6      PacketParser.map.<anonymous closure> (package:socket_io_common/src/engine/parser/parser.dart:229:25)
#7      _rootRunUnary (dart:async/zone.dart:1198:47)
#8      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#13     Future.wait.<anonymous closure> (dart:async/future.dart:410:22)
#14     _rootRunUnary (dart:async/zone.dart:1198:47)
#15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#19     Future._complete (dart:async/future_impl.dart:519:7)
#20     new Future.microtask.<anonymous closure> (dart:async/future.dart:201:16)
#21     _rootRun (dart:async/zone.dart:1182:47)
#22     _CustomZone.run (dart:async/zone.dart:1093:19)
#23     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#25     _rootRun (dart:async/zone.dart:1190:13)
#26     _CustomZone.run (dart:async/zone.dart:1093:19)
#27     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#29     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#31     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

```

**Comment by jumperchen** [comment]
The code you ran is two part of the example into one file, you should run it separately as this - https://github.com/rikulo/socket.io-client-dart/tree/master/test
One for server, one for client.

**Comment by irfanbacker** [comment]
Hi. So what i found is that, the documentation is somewhat confusing. The example given for client in the readme contains no transport header. That was the problem. The documentation could be improved.

**Comment by irfanbacker** [comment]
> The code you ran is two part of the example into one file, you should run it separately as this - https://github.com/rikulo/socket.io-client-dart/tree/master/test
> One for server, one for client.

So what i found is that, the documentation is somewhat confusing. The example given for client in the readme contains no transport header. That was the problem. The documentation could be improved.

**Comment by jumperchen** [comment]
The `transports` header is used for `dart:io` client and for browser client the header is not must.
